# Generated by Django 6.0.5 on 2026-05-14 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Treść pytania')),
                ('audio_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Zewnętrzny link do audio')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='quiz_audio/', verbose_name='Własny plik audio')),
                ('time_limit', models.IntegerField(default=15, verbose_name='Limit czasu (sekundy)')),
                ('points', models.IntegerField(default=1, verbose_name='Punkty')),
                ('min_points', models.IntegerField(default=0, verbose_name='Minimalne punkty')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Koniec')),
                ('total_points', models.IntegerField(default=0, verbose_name='Suma punktow')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Poprawne')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Wszystkie pytania')),
                ('total_time_seconds', models.FloatField(default=0, verbose_name='Czas laczny')),
                ('average_time_seconds', models.FloatField(default=0, verbose_name='Sredni czas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Treść odpowiedzi')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Czy poprawna?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='projekt_muzyka.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Odpowiedz')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Poprawna')),
                ('time_taken_seconds', models.FloatField(default=0, verbose_name='Czas odpowiedzi')),
                ('points_awarded', models.IntegerField(default=0, verbose_name='Punkty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='projekt_muzyka.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='projekt_muzyka.answer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='projekt_muzyka.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='quiz_covers/', verbose_name='Okładka')),
                ('difficulty', models.CharField(choices=[('EASY', 'Łatwy'), ('MEDIUM', 'Średni'), ('HARD', 'Trudny')], default='MEDIUM', max_length=10, verbose_name='Poziom trudności')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='projekt_muzyka.genre', verbose_name='Gatunek')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projekt_muzyka.quiz'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projekt_muzyka.quiz'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytul')),
                ('artist', models.CharField(blank=True, max_length=200, null=True, verbose_name='Artysta')),
                ('apple_snippet_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Apple Music snippet')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='song_audio/', verbose_name='Plik audio')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Rok wydania')),
                ('duration_seconds', models.IntegerField(default=30, verbose_name='Dlugosc (sekundy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='projekt_muzyka.genre', verbose_name='Gatunek')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='projekt_muzyka.song', verbose_name='Piosenka'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa wyswietlana')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Aktualna seria')),
                ('best_streak', models.IntegerField(default=0, verbose_name='Najlepsza seria')),
                ('total_points', models.IntegerField(default=0, verbose_name='Suma punktow')),
                ('games_played', models.IntegerField(default=0, verbose_name='Gier')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Poprawne odpowiedzi')),
                ('total_answers', models.IntegerField(default=0, verbose_name='Wszystkie odpowiedzi')),
                ('total_time_seconds', models.FloatField(default=0, verbose_name='Czas laczny')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Wynik')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Poprawne')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Wszystkie pytania')),
                ('average_time_seconds', models.FloatField(default=0, verbose_name='Sredni czas')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Data gry')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='projekt_muzyka.quiz')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score', to='projekt_muzyka.gamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
