# Generated by Django 6.0.5 on 2026-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_questions_to_ask',
            field=models.IntegerField(default=10, verbose_name='Liczba pytań w grze'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, default='', verbose_name='Treść pytania'),
        ),
    ]
