# Generated by Django 6.0.5 on 2026-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0002_quiz_num_questions_to_ask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=15, verbose_name='Długość odtwarzania utworu (sekundy)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Limit czasu (sekundy) - jeśli puste, dziedziczy z Quizu'),
        ),
    ]
