# Generated by Django 6.0.5 on 2026-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0003_quiz_time_limit_alter_question_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='chosen_difficulty',
            field=models.CharField(choices=[('EASY', 'Łatwy'), ('MEDIUM', 'Średni'), ('HARD', 'Trudny')], default='MEDIUM', max_length=10, verbose_name='Wybrana trudność'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='chosen_num_questions',
            field=models.IntegerField(default=10, verbose_name='Wybrana liczba pytań'),
        ),
    ]
