# Generated by Django 6.0.5 on 2026-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0004_gamesession_chosen_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Artysta'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Tytul'),
        ),
    ]
