# Generated by Django 6.0.5 on 2026-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0005_alter_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_random',
            field=models.BooleanField(default=False, verbose_name='Czy losowy?'),
        ),
    ]
