# Generated by Django 6.0.5 on 2026-05-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0006_quiz_is_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_category',
            field=models.BooleanField(default=False, verbose_name='Czy główna kategoria'),
        ),
        migrations.AddField(
            model_name='song',
            name='apple_raw_genre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Surowy gatunek Apple Music'),
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_songs', to='projekt_muzyka.genre', verbose_name='Kategoria główna'),
        ),
    ]
