# Generated by Django 6.0.5 on 2026-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0007_genre_is_category_song_apple_raw_genre_song_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='imported_from_playlist_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Importowano z playlisty (URL)'),
        ),
    ]
