# Generated by Django 6.0.5 on 2026-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_muzyka', '0008_quiz_imported_from_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='banner_vertical_position',
            field=models.IntegerField(default=35, verbose_name='Pozycja pionowa baneru (%)'),
        ),
    ]
